apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-cillium
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/3_gateway_cillium
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps-of-apps
