---
- name: Setup HAProxy & Security
  hosts: haproxy
  become: true
  vars:
    # Ton réseau VPN + Réseau local
    vpn_subnet: "192.168.50.0/24 10.0.0.0/8"
    worker_ips: "{{ worker_ips | default(['192.168.50.120', '192.168.50.121', '192.168.50.122']) }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install HAProxy & Tools
      apt:
        name: [haproxy, curl, gnupg, rsyslog, console-setup]
        state: latest

    - name: Configure keyboard layout to FR
      lineinfile:
        path: /etc/default/keyboard
        regexp: "^XKBLAYOUT="
        line: 'XKBLAYOUT="fr"'
      notify: Reload Keyboard

    - name: Deploy HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        validate: haproxy -c -f %s
      notify: Restart HAProxy

    # --- CROWDSEC ---
    - name: Download CrowdSec GPG key
      get_url:
        url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
        dest: /usr/share/keyrings/crowdsec_crowdsec-archive-keyring.asc
        mode: '0644'
        force: true

    - name: Remove incompatible CrowdSec repo list (Trixie cleanup)
      file:
        path: /etc/apt/sources.list.d/crowdsec_crowdsec.list
        state: absent

    - name: Add CrowdSec Repository (Bookworm compat)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.asc] https://packagecloud.io/crowdsec/crowdsec/debian/ bookworm main"
        state: present
        filename: crowdsec_crowdsec

    - name: Install CrowdSec & Bouncer
      apt:
        name: [crowdsec, crowdsec-firewall-bouncer]
        state: latest

    - name: Ensure CrowdSec detects HAProxy
      command: cscli collections install crowdsecurity/haproxy
      register: cscli
      changed_when: "'Example' not in cscli.stdout"
      ignore_errors: yes
      notify: Reload CrowdSec

  handlers:
    - name: Restart HAProxy
      service: { name: haproxy, state: restarted }
    - name: Reload CrowdSec
      systemd: { name: crowdsec, state: reloaded }

    - name: Reload Keyboard
      service: { name: console-setup, state: restarted }
