---
- name: Setup HAProxy & Security
  hosts: haproxy
  become: true
  vars:
    # Ton réseau VPN + Réseau local
    vpn_subnet: "192.168.50.0/24 10.0.0.0/8"
    worker_ips: "{{ worker_ips | default(['192.168.50.120', '192.168.50.121', '192.168.50.122']) }}"
    # L'IP vers laquelle le DNS *.private.local doit pointer (Ton HAProxy)
    haproxy_bind_ip: "192.168.50.200"
  tasks:
    - name: Ensure DNS is working (Fix for missing systemd-resolved)
      copy:
        dest: /etc/resolv.conf
        content: "nameserver 1.1.1.1\nnameserver 8.8.8.8"
        force: yes

    - name: Remove resolvconf (conflicts with manual setup)
      apt:
        name: resolvconf
        state: absent
        purge: yes

    - name: Configure dnsmasq to ignore resolvconf (Silence logs)
      lineinfile:
        path: /etc/default/dnsmasq
        regexp: '^IGNORE_RESOLVCONF='
        line: 'IGNORE_RESOLVCONF=yes'
        create: yes
      notify: Restart Dnsmasq

    # --- FIX CONFLIT PORT 53 ---
    # Moved BEFORE install to ensure port 53 is free when dnsmasq starts
    - name: Disable systemd-resolved to free port 53
      service:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install HAProxy & Tools
      apt:
        name: [haproxy, curl, gnupg, rsyslog, console-setup, dnsmasq, dnsutils]
        state: latest

    - name: Configure keyboard layout to FR
      lineinfile:
        path: /etc/default/keyboard
        regexp: "^XKBLAYOUT="
        line: 'XKBLAYOUT="fr"'
      notify: Reload Keyboard

    - name: Deploy HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        validate: haproxy -c -f %s
      notify: Restart HAProxy

    # --- DNSMASQ (Split-Horizon) ---
    - name: Configure DNS wildcard for .private.local
      copy:
        dest: /etc/dnsmasq.d/homelab.conf
        content: |
          # Redirection de tout le domaine *.private.local vers HAProxy
          address=/.private.local/{{ haproxy_bind_ip }}
        mode: '0644'
      notify: Restart Dnsmasq

    # --- CROWDSEC ---
    - name: Download CrowdSec GPG key
      get_url:
        url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
        dest: /usr/share/keyrings/crowdsec_crowdsec-archive-keyring.asc
        mode: '0644'
        force: true

    - name: Remove incompatible CrowdSec repo list (Trixie cleanup)
      file:
        path: /etc/apt/sources.list.d/crowdsec_crowdsec.list
        state: absent

    - name: Add CrowdSec Repository (Bookworm compat)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.asc] https://packagecloud.io/crowdsec/crowdsec/debian/ bookworm main"
        state: present
        filename: crowdsec_crowdsec

    - name: Install CrowdSec & Bouncer
      apt:
        name: [crowdsec, crowdsec-firewall-bouncer]
        state: latest

    - name: Ensure CrowdSec detects HAProxy
      command: cscli collections install crowdsecurity/haproxy
      register: cscli
      changed_when: "'Example' not in cscli.stdout"
      ignore_errors: yes
      notify: Reload CrowdSec

# --- FIX VPN ACCESS (Corrige l'erreur "ignoring query from non-local") ---
    - name: Disable Dnsmasq local-service restriction (Allow VPN)
      replace:
        path: /usr/share/dnsmasq/init-system-common
        regexp: '--local-service'
        replace: ''
      notify:
        - Reload Systemd
        - Restart Dnsmasq

  handlers:
    - name: Reload Systemd
      systemd:
        daemon_reload: yes

    - name: Restart HAProxy
      service: { name: haproxy, state: restarted }

    - name: Restart Dnsmasq
      service: { name: dnsmasq, state: restarted }

    - name: Reload CrowdSec
      systemd: { name: crowdsec, state: reloaded }

    - name: Reload Keyboard
      service: { name: console-setup, state: restarted }
